version: "3"
services:
  app:
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      PYTHONUNBUFFERED: 1
      POSTGRESS_HOST: database
    links:
      - "database:database"
    depends_on:
      - database
    volumes: 
      - D:\Projects\EXPERIMENTAL_AREA\centrifugal_deneme\datas\images:/app/media
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: chat_system
    ports:
      - 5432:5432
    volumes: 
      - D:\Projects\EXPERIMENTAL_AREA\centrifugal_deneme\datas\data:/var/lib/postgresql/data
     # - ./config/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
  redis:
    image: redis
    ports:
      - 6379:6379
  centrifugo:
    image: centrifugo/centrifugo
    volumes:
      - ./config/centrifugo.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8001:8001
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    restart: always
    depends_on:
      - redis
      - app
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9000:9000
    restart: always
    command: 'bash -c "nginx -g ''daemon off;''"'
    depends_on:
      - centrifugo
      - database
      - app
      - redis
networks:
    backend-network:
        driver: bridge