# Generated by Django 3.0.5 on 2021-05-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile image of User', upload_to='profile_images/'),
        ),
    ]
