# Generated by Django 3.0.5 on 2021-05-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(default='common/mx.jpeg', help_text='Profile image of User', upload_to='profile_image/'),
        ),
    ]
